version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: meu-postgres
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: lojadb
    ports:
      - "5432:5432"