# Configuração de Produção (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/lojadb
spring.datasource.username=usuario
spring.datasource.password=senha123
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desabilita explicitamente o H2 Console neste perfil para evitar confusão
spring.h2.console.enabled=false